import { Link } from "react-router-dom";

const moments = [["Cocktails", "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=85"], ["Small plates", "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85"], ["Good company", "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=900&q=85"]];
function HomePage() {
  return <div className="space-y-16 sm:space-y-24">
    <section className="relative overflow-hidden rounded-[2rem] bg-stone-900"><img className="absolute inset-0 h-full w-full object-cover opacity-60" src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1800&q=90" alt="Cocktail at Dangi Restorent"/><div className="absolute inset-0 bg-gradient-to-r from-stone-950 via-stone-950/70 to-stone-950/10"/><div className="relative min-h-[560px] px-6 py-16 sm:flex sm:min-h-[630px] sm:items-center sm:px-12 lg:px-20"><div className="max-w-2xl"><p className="eyebrow">Your table is waiting</p><h1 className="mt-4 font-serif text-5xl font-bold leading-[.95] text-white sm:text-7xl">Come for the flavour.<br/><em className="font-normal text-amber-300">Stay for the feeling.</em></h1><p className="mt-7 max-w-lg text-base leading-8 text-stone-200 sm:text-lg">An all-day kitchen and late-night lounge, with fireside cocktails, seasonal food and a seat saved just for you.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/reserve" className="rounded-full bg-amber-400 px-6 py-3 font-bold text-stone-950 transition hover:bg-amber-300">Book a table</Link><Link to="/menu" className="rounded-full border border-white/30 px-6 py-3 font-bold text-white transition hover:bg-white hover:text-stone-950">Explore the menu</Link></div></div></div></section>
    <section className="grid items-center gap-10 lg:grid-cols-2 lg:gap-16"><div><p className="eyebrow">A seat at Dangi</p><h2 className="mt-3 font-serif text-4xl font-bold leading-tight text-white sm:text-5xl">A warm welcome, morning to midnight.</h2><p className="mt-5 max-w-xl leading-8 text-stone-400">We believe the best nights begin around a table. Settle in for vibrant plates, generous pours and the kind of conversations that make you lose track of time.</p><Link to="/about" className="mt-7 inline-block font-bold text-amber-300 underline decoration-amber-300/40 underline-offset-8 hover:text-amber-200">Meet the Dangi family →</Link></div><div className="grid grid-cols-2 gap-4"><img className="mt-10 h-64 w-full rounded-[1.5rem] object-cover sm:h-80" src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=85" alt="Seasonal dish"/><img className="h-64 w-full rounded-[1.5rem] object-cover sm:h-80" src="https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=85" alt="Craft cocktail"/></div></section>
    <section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">A Dangi evening</p><h2 className="mt-3 font-serif text-4xl font-bold text-white">Made to be shared.</h2></div><Link to="/gallery" className="font-bold text-amber-300 hover:text-amber-200">See the gallery →</Link></div><div className="mt-8 grid gap-5 sm:grid-cols-3">{moments.map(([title,image]) => <Link key={title} to="/gallery" className="group relative h-72 overflow-hidden rounded-[1.5rem]"><img className="h-full w-full object-cover transition duration-500 group-hover:scale-110" src={image} alt={title}/><span className="absolute inset-0 flex items-end bg-gradient-to-t from-black/75 to-transparent p-6 font-serif text-3xl font-bold text-white">{title}</span></Link>)}</div></section>
    <section className="rounded-[2rem] border border-amber-300/20 bg-amber-300/10 p-7 text-center sm:p-12"><p className="eyebrow">Make an occasion of it</p><h2 className="mt-3 font-serif text-4xl font-bold text-white sm:text-5xl">Your next favourite night starts here.</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-stone-300">Reserve a table for dinner, drinks or your next celebration.</p><Link to="/reserve" className="mt-7 inline-block rounded-full bg-amber-400 px-6 py-3 font-bold text-stone-950 hover:bg-amber-300">Reserve a table</Link></section>
  </div>;
}
export default HomePage;
